// filepath: c:\Users\cegar\proyectos\amazon_store_nextjs\src\app\layout.js
import { Inter, Roboto_Mono } from "next/font/google";

import NavegationMenu from "@/components/NavegationMenu";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Amazon",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const {category} = await params;

  return (
    
      <div className="p-0 m-0">
        <NavegationMenu category={category}/>
        {children}
      </div>
    
  );
}
